### ISSUE TITLE
Suggested clarification about `:%s/…/…/g`

### ISSUE THREAD

**Issue by RichardBronosky** [peacefixation/peacefixation.github.io#1]
I really like your writings here! I just learned about using `:%normal!` to repeat a macro. I am a macro fiend. I'm going to get a lot of use out of that.

https://github.com/peacefixation/peacefixation.github.io/blob/cf190df59ac9e629994554c88875bc07439a3d84/development/2017/08/30/vim-add-offset-macro.html#L145

In the paragraph...

> <p>What's this doing? Well <code>:</code> enters command mode and <code>%</code> selects the whole
> buffer. Then <code>s</code> is the substitute command and we find the end of each line with
> <code>$</code> (which is a zero length match) and replace (well, replacing nothing with something is
> more like insert) it with a <code>,</code> and <span style='background: #fdd'>we specify the <code>g</code>
> (global) flag so we keep replacing after the first match</span>. So now we have a comma after each number, and
> it's easy to go from this:</p>

When you say "we specify the g (global) flag so we keep replacing after the first match" that's not entirely accurate. What the `g` flag does is "keep replacing after the first match **on each line**". So in your case since you are matching `$`, there can only be 1 match per line and therefore your `g` flag is superfluous. It doesn't hurt anything. I only mention it because this is an instructional writing and you are likely to mislead your readers. You probably already know everything I've said.

**Comment by peacefixation** [comment]
Thanks for catching that slip, I'll make an edit to the post. Glad you enjoyed reading it, I'm still a vim noob, I use it just enough to be dangerous.

**Comment by peacefixation** [comment]
I applied the fix, and ... took a few days to rebuild my blog with Hugo instead of Jekyll. About time I showed this thing some love. Thanks again!
